/*////////////////////////////////////////////////////////////////////////////*/

DEF_ETICK(daisy);
DEF_ETICK(bramble);
DEF_ETICK(hedge_wall);
DEF_ETICK(bell_plant);
DEF_ETICK(rocket_plant);
DEF_ETICK(walker);
DEF_ETICK(dripper);
DEF_ETICK(goliath);
DEF_ETICK(bell_missile);
DEF_ETICK(rocket);
DEF_ETICK(coin);
DEF_ETICK(explosion);

enum: nkU32
{

EntityID_None,
// Plants
EntityID_Daisy,
EntityID_Bramble,
EntityID_HedgeWall,
EntityID_BellPlant,
EntityID_RocketPlant,
// Monsters
EntityID_Grunt,
EntityID_Soldier,
EntityID_Barbarian,
EntityID_Dripper,
EntityID_Goliath,
// Bullets
EntityID_Pollen,
EntityID_BellMissile,
EntityID_Rocket,
EntityID_Tarball,
// Other
EntityID_HomeTree,
EntityID_CoinCopper,
EntityID_CoinSilver,
EntityID_CoinGold,
EntityID_Explosion,
EntityID_TOTAL

};

INTERNAL constexpr EntityDesc ENTITY_TABLE[] =
{

// EntityID_None
{
/* Texture            */ NULL,
/* Animation          */ NULL,
/* Type               */ EntityType_None,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ NULL,
/* Health             */ 0.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 0.0f,
/* Radius             */ 0.0f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 0.0f,0.0f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_Daisy
{
/* Texture            */ "entity/daisy.png",
/* Animation          */ "entity/daisy.anm",
/* Type               */ EntityType_Plant,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(daisy),
/* Health             */ 5.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 5.0f,
/* Radius             */ 0.3f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,-0.4f },
/* Bounds             */ { 1.0f,1.0f },
/* Growth Phases      */ { 10,15,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_Bramble
{
/* Texture            */ "entity/bramble.png",
/* Animation          */ "entity/bramble.anm",
/* Type               */ EntityType_Plant,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_NotEdible|EntityFlag_NotShootable|EntityFlag_DrawFirst,
/* Tick               */ ETICK(bramble),
/* Health             */ 5.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 0.0f,
/* Radius             */ 0.3f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 1.0f,1.0f },
/* Growth Phases      */ { 60,90,150,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_HedgeWall
{
/* Texture            */ "entity/hedge_wall.png",
/* Animation          */ "entity/hedge_wall.anm",
/* Type               */ EntityType_Plant,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(hedge_wall),
/* Health             */ 40.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 0.0f,
/* Radius             */ 0.4f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,-0.5f },
/* Bounds             */ { 1.0f,1.0f },
/* Growth Phases      */ { 20,200,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_BellPlant
{
/* Texture            */ "entity/bell_plant.png",
/* Animation          */ "entity/bell_plant.anm",
/* Type               */ EntityType_Plant,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(bell_plant),
/* Health             */ 5.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 7.0f,
/* Radius             */ 0.3f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,-0.3f },
/* Bounds             */ { 1.0f,1.0f },
/* Growth Phases      */ { 10,15,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_RocketPlant
{
/* Texture            */ "entity/rocket_plant.png",
/* Animation          */ "entity/rocket_plant.anm",
/* Type               */ EntityType_Plant,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(rocket_plant),
/* Health             */ 7.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 10.0f,
/* Radius             */ 0.3f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 1.0f,1.0f },
/* Growth Phases      */ { 3,5,10,15,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_Grunt
{
/* Texture            */ "entity/grunt.png",
/* Animation          */ "entity/grunt.anm",
/* Type               */ EntityType_Monster,
/* Default State      */ EntityState_Move,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(walker),
/* Health             */ 6.0f,
/* Damage             */ 1.0f,
/* Speed              */ 0.5f,
/* Range              */ 0.0f,
/* Radius             */ 0.3f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,-0.25f },
/* Bounds             */ { 1.0f,1.0f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { "splat_wet_000.wav","splat_wet_001.wav","splat_wet_002.wav",NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ "tar_explosion",
/* Death Particle     */ "tar_blobs_small",
/* Death Particle Min */ 18,
/* Death Particle Max */ 26,
/* Death Decal        */ "tar_splat_large",
/* Death Decal Min    */ 8,
/* Death Decal Max    */ 12,
/* Coin Drop Chance   */ 20,
/* Coin Drop Min      */ 1,
/* Coin Drop Max      */ 4,
},

// EntityID_Soldier
{
/* Texture            */ "entity/soldier.png",
/* Animation          */ "entity/soldier.anm",
/* Type               */ EntityType_Monster,
/* Default State      */ EntityState_Move,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(walker),
/* Health             */ 10.0f,
/* Damage             */ 1.0f,
/* Speed              */ 0.65f,
/* Range              */ 4.0f,
/* Radius             */ 0.3f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,-0.25f },
/* Bounds             */ { 1.0f,1.0f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { "splat_wet_000.wav","splat_wet_001.wav","splat_wet_002.wav",NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ "tar_explosion",
/* Death Particle     */ "tar_blobs_small",
/* Death Particle Min */ 18,
/* Death Particle Max */ 26,
/* Death Decal        */ "tar_splat_large",
/* Death Decal Min    */ 8,
/* Death Decal Max    */ 12,
/* Coin Drop Chance   */ 20,
/* Coin Drop Min      */ 1,
/* Coin Drop Max      */ 5,
},

// EntityID_Barbarian
{
/* Texture            */ "entity/barbarian.png",
/* Animation          */ "entity/barbarian.anm",
/* Type               */ EntityType_Monster,
/* Default State      */ EntityState_Move,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(walker),
/* Health             */ 14.0f,
/* Damage             */ 1.0f,
/* Speed              */ 1.0f,
/* Range              */ 0.0f,
/* Radius             */ 0.3f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,-0.25f },
/* Bounds             */ { 1.0f,1.0f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { "splat_wet_000.wav","splat_wet_001.wav","splat_wet_002.wav",NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ "tar_explosion",
/* Death Particle     */ "tar_blobs_small",
/* Death Particle Min */ 18,
/* Death Particle Max */ 26,
/* Death Decal        */ "tar_splat_large",
/* Death Decal Min    */ 8,
/* Death Decal Max    */ 12,
/* Coin Drop Chance   */ 20,
/* Coin Drop Min      */ 2,
/* Coin Drop Max      */ 5,
},

// EntityID_Dripper
{
/* Texture            */ "entity/dripper.png",
/* Animation          */ "entity/dripper.anm",
/* Type               */ EntityType_Monster,
/* Default State      */ EntityState_Move,
/* Flags              */ EntityFlag_Aerial,
/* Tick               */ ETICK(dripper),
/* Health             */ 10.0f,
/* Damage             */ 1.0f,
/* Speed              */ 0.5f,
/* Range              */ 0.0f,
/* Radius             */ 0.3f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,-0.25f },
/* Bounds             */ { 1.0f,1.0f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { "splat_wet_000.wav","splat_wet_001.wav","splat_wet_002.wav",NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ "tar_explosion",
/* Death Particle     */ "tar_blobs_small",
/* Death Particle Min */ 24,
/* Death Particle Max */ 32,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 10,
/* Coin Drop Min      */ 3,
/* Coin Drop Max      */ 7,
},

// EntityID_Goliath
{
/* Texture            */ "entity/goliath.png",
/* Animation          */ "entity/goliath.anm",
/* Type               */ EntityType_Monster,
/* Default State      */ EntityState_Move,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(goliath),
/* Health             */ 500.0f,
/* Damage             */ 5.0f,
/* Speed              */ 0.125f,
/* Range              */ 0.0f,
/* Radius             */ 1.1f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,-0.25f },
/* Bounds             */ { 4.0f,3.0f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { "splat_wet_000.wav","splat_wet_001.wav","splat_wet_002.wav",NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ "tar_explosion",
/* Death Particle     */ "tar_blobs_small",
/* Death Particle Min */ 150,
/* Death Particle Max */ 200,
/* Death Decal        */ "tar_splat_large",
/* Death Decal Min    */ 80,
/* Death Decal Max    */ 100,
/* Coin Drop Chance   */ 25,
/* Coin Drop Min      */ 12,
/* Coin Drop Max      */ 24,
},

// EntityID_Pollen
{
/* Texture            */ "entity/pollen.png",
/* Animation          */ "entity/pollen.anm",
/* Type               */ EntityType_Bullet,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ NULL,
/* Health             */ 1.0f,
/* Damage             */ 2.0f,
/* Speed              */ 5.0f,
/* Range              */ 6.0f,
/* Radius             */ 0.1f,
/* Z-Depth            */ 0.5f,
/* Collision Mask     */ EntityType_Monster,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 0.5f,0.5f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { "splat_000.wav","splat_001.wav","splat_002.wav",NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_BellMissile
{
/* Texture            */ "entity/bell_missile.png",
/* Animation          */ "entity/bell_missile.anm",
/* Type               */ EntityType_Bullet,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_Aerial,
/* Tick               */ ETICK(bell_missile),
/* Health             */ 1.0f,
/* Damage             */ 1.5f,
/* Speed              */ 2.5f,
/* Range              */ 8.0f,
/* Radius             */ 0.1f,
/* Z-Depth            */ 1.0f,
/* Collision Mask     */ EntityType_Monster,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 0.5f,0.5f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { "splat_000.wav","splat_001.wav","splat_002.wav",NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_Rocket
{
/* Texture            */ "entity/rocket.png",
/* Animation          */ "entity/rocket.anm",
/* Type               */ EntityType_Bullet,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(rocket),
/* Health             */ 1.0f,
/* Damage             */ 40.0f,
/* Speed              */ 7.5f,
/* Range              */ 25.0f,
/* Radius             */ 0.3f,
/* Z-Depth            */ 0.5f,
/* Collision Mask     */ EntityType_Monster,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 0.5f,0.5f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_Tarball
{
/* Texture            */ "entity/tarball.png",
/* Animation          */ "entity/tarball.anm",
/* Type               */ EntityType_Bullet,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ NULL,
/* Health             */ 1.0f,
/* Damage             */ 1.0f,
/* Speed              */ 5.0f,
/* Range              */ 6.0f,
/* Radius             */ 0.1f,
/* Z-Depth            */ 0.5f,
/* Collision Mask     */ EntityType_Plant,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 0.5f,0.5f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { "splat_000.wav","splat_001.wav","splat_002.wav",NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_HomeTree
{
/* Texture            */ "entity/home_tree.png",
/* Animation          */ "entity/home_tree.anm",
/* Type               */ EntityType_Base,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ NULL,
/* Health             */ 100.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 0.0f,
/* Radius             */ 1.4f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,-0.8f },
/* Bounds             */ { 3.0f,3.0f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_CoinCopper
{
/* Texture            */ "entity/coin_copper.png",
/* Animation          */ "entity/coin_copper.anm",
/* Type               */ EntityType_Item,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(coin),
/* Health             */ 1.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 0.0f,
/* Radius             */ 0.4f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 0.3f,0.3f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_CoinSilver
{
/* Texture            */ "entity/coin_silver.png",
/* Animation          */ "entity/coin_silver.anm",
/* Type               */ EntityType_Item,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(coin),
/* Health             */ 1.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 0.0f,
/* Radius             */ 0.4f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 0.35f,0.35f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_CoinGold
{
/* Texture            */ "entity/coin_gold.png",
/* Animation          */ "entity/coin_gold.anm",
/* Type               */ EntityType_Item,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(coin),
/* Health             */ 1.0f,
/* Damage             */ 0.0f,
/* Speed              */ 0.0f,
/* Range              */ 0.0f,
/* Radius             */ 0.4f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 0.4f,0.4f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

// EntityID_Explosion
{
/* Texture            */ "entity/explosion.png",
/* Animation          */ "entity/explosion.anm",
/* Type               */ EntityType_Other,
/* Default State      */ EntityState_Idle,
/* Flags              */ EntityFlag_None,
/* Tick               */ ETICK(explosion),
/* Health             */ 1.0f,
/* Damage             */ 150.0f,
/* Speed              */ 0.0f,
/* Range              */ 0.0f,
/* Radius             */ 2.5f,
/* Z-Depth            */ 0.0f,
/* Collision Mask     */ EntityType_None,
/* Draw Offset        */ { 0.0f,0.0f },
/* Bounds             */ { 0.0f,0.0f },
/* Growth Phases      */ { 0,0,0,0,0,0,0,0 },
/* Death Sounds       */ { NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL },
/* Death Effect       */ NULL,
/* Death Particle     */ NULL,
/* Death Particle Min */ 0,
/* Death Particle Max */ 0,
/* Death Decal        */ NULL,
/* Death Decal Min    */ 0,
/* Death Decal Max    */ 0,
/* Coin Drop Chance   */ 0,
/* Coin Drop Min      */ 0,
/* Coin Drop Max      */ 0,
},

}; // ENTITY_TABLE

NK_STATIC_ASSERT(NK_ARRAY_SIZE(ENTITY_TABLE) == EntityID_TOTAL, entity_table_size_mismatch);

/*////////////////////////////////////////////////////////////////////////////*/
